### ISSUE TITLE
Problema al subir presentacion User story & Use cases

### ISSUE THREAD

**Issue by suarezfran** [IngSoft-FIS-2023-2/investigacion-tecnologia-N4A#1]
@patricia-deleon No me esta dejando hacer push a main para subir el .md y la presentacion.

Copio el log de error:

remote: Permission to IngSoft-FIS-2023-2/investigacion-tecnologia-N4A.git denied to Fran313.
fatal: unable to access '[https://github.com/IngSoft-FIS-2023-2/investigacion-tecnologia-N4A.git/':](https://github.com/IngSoft-FIS-2023-2/investigacion-tecnologia-N4A.git/%27:) The requested URL returned error: 403

**Comment by patricia-deleon** [comment]
@Fran313 Ya te agregué permisos en ese repo.

**Comment by suarezfran** [comment]
@patricia-deleon Ya quedo subido! Gracias!
